# Generated by Django 6.0.3 on 2026-03-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_text', models.TextField()),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('hi', 'Hindi'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('accent', models.CharField(choices=[('com', 'US English (default)'), ('co.uk', 'British English'), ('com.au', 'Australian English'), ('ca', 'Canadian English'), ('co.in', 'Indian English')], default='com', max_length=20)),
                ('speed', models.CharField(choices=[('normal', 'Normal'), ('slow', 'Slow')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('audio_path', models.CharField(blank=True, default='', max_length=500)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('video_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Story Job',
                'verbose_name_plural': 'Story Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TTSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('hi', 'Hindi'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('accent', models.CharField(choices=[('com', 'US English (default)'), ('co.uk', 'British English'), ('com.au', 'Australian English'), ('ca', 'Canadian English'), ('co.in', 'Indian English')], default='com', max_length=20)),
                ('speed', models.CharField(choices=[('normal', 'Normal'), ('slow', 'Slow')], default='normal', max_length=10)),
            ],
            options={
                'verbose_name': 'TTS Settings',
                'verbose_name_plural': 'TTS Settings',
            },
        ),
    ]
