# Generated by Django 6.0.3 on 2026-03-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyjob',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon — bright colors, flat design, child-friendly'), ('realistic', 'Realistic — photographic, detailed'), ('watercolor', 'Watercolor — soft brush strokes, painterly'), ('comic', 'Comic Book — bold outlines, halftone, panel style'), ('anime', 'Anime — Japanese animation style'), ('pixel', 'Pixel Art — retro 8-bit style'), ('sketch', 'Sketch — pencil drawing, black and white')], default='cartoon', max_length=20),
        ),
        migrations.AddField(
            model_name='ttssettings',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon — bright colors, flat design, child-friendly'), ('realistic', 'Realistic — photographic, detailed'), ('watercolor', 'Watercolor — soft brush strokes, painterly'), ('comic', 'Comic Book — bold outlines, halftone, panel style'), ('anime', 'Anime — Japanese animation style'), ('pixel', 'Pixel Art — retro 8-bit style'), ('sketch', 'Sketch — pencil drawing, black and white')], default='cartoon', max_length=20),
        ),
    ]
