# Generated by Django 6.0.3 on 2026-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0002_storyjob_image_style_ttssettings_image_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating_audio', 'Generating Audio'), ('audio_done', 'Audio Done'), ('generating_image', 'Generating Image'), ('image_done', 'Image Done'), ('generating_video', 'Generating Video'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
