# Generated by Django 6.0.3 on 2026-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0003_alter_storyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyjob',
            name='format',
            field=models.CharField(choices=[('normal', 'Normal (16:9 Landscape)'), ('tiktok', 'TikTok (9:16 Vertical)')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='ttssettings',
            name='format',
            field=models.CharField(choices=[('normal', 'Normal (16:9 Landscape)'), ('tiktok', 'TikTok (9:16 Vertical)')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon'), ('realistic', 'Realistic'), ('watercolor', 'Watercolor'), ('comic', 'Comic Book'), ('anime', 'Anime'), ('pixel', 'Pixel Art'), ('sketch', 'Sketch')], default='cartoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttssettings',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon'), ('realistic', 'Realistic'), ('watercolor', 'Watercolor'), ('comic', 'Comic Book'), ('anime', 'Anime'), ('pixel', 'Pixel Art'), ('sketch', 'Sketch')], default='cartoon', max_length=20),
        ),
    ]
