# Generated by Django 6.0.3 on 2026-03-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0004_storyjob_format_ttssettings_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyjob',
            name='rewritten_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rewriting_story', 'Rewriting Story'), ('story_rewritten', 'Story Rewritten'), ('generating_audio', 'Generating Audio'), ('audio_done', 'Audio Done'), ('generating_image', 'Generating Image'), ('image_done', 'Image Done'), ('generating_video', 'Generating Video'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
