# Generated by Django 6.0.3 on 2026-03-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0005_storyjob_rewritten_text_alter_storyjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyjob',
            name='audio_path',
        ),
        migrations.RemoveField(
            model_name='storyjob',
            name='image_path',
        ),
        migrations.AddField(
            model_name='storyjob',
            name='completed_segments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storyjob',
            name='total_segments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rewriting_story', 'Rewriting Story'), ('story_rewritten', 'Story Rewritten'), ('splitting_story', 'Splitting Story'), ('processing_segments', 'Processing Segments'), ('merging_video', 'Merging Video'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='StorySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('text', models.TextField()),
                ('audio_path', models.CharField(blank=True, default='', max_length=500)),
                ('image_path', models.CharField(blank=True, default='', max_length=500)),
                ('clip_path', models.CharField(blank=True, default='', max_length=500)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='video_pipeline.storyjob')),
            ],
            options={
                'verbose_name': 'Story Segment',
                'verbose_name_plural': 'Story Segments',
                'ordering': ['order'],
            },
        ),
    ]
