# Generated by Django 6.0.3 on 2026-03-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0006_remove_storyjob_audio_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyjob',
            name='voice_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='ttssettings',
            name='voice_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='accent',
            field=models.CharField(choices=[('com', 'US English'), ('co.uk', 'British English'), ('com.au', 'Australian English'), ('ca', 'Canadian English'), ('co.in', 'Indian English'), ('ie', 'Irish English'), ('co.za', 'South African English'), ('com.ng', 'Nigerian English')], default='com', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon'), ('realistic', 'Realistic'), ('watercolor', 'Watercolor'), ('comic', 'Comic Book'), ('anime', 'Anime'), ('ghibli', 'Studio Ghibli'), ('pixel', 'Pixel Art'), ('sketch', 'Sketch')], default='cartoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyjob',
            name='speed',
            field=models.CharField(choices=[('0.5', '0.5× Very Slow'), ('0.75', '0.75× Slow'), ('1.0', '1.0× Normal'), ('1.25', '1.25× Fast'), ('1.5', '1.5× Faster'), ('2.0', '2.0× Very Fast')], default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='ttssettings',
            name='accent',
            field=models.CharField(choices=[('com', 'US English'), ('co.uk', 'British English'), ('com.au', 'Australian English'), ('ca', 'Canadian English'), ('co.in', 'Indian English'), ('ie', 'Irish English'), ('co.za', 'South African English'), ('com.ng', 'Nigerian English')], default='com', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttssettings',
            name='image_style',
            field=models.CharField(choices=[('cartoon', 'Cartoon'), ('realistic', 'Realistic'), ('watercolor', 'Watercolor'), ('comic', 'Comic Book'), ('anime', 'Anime'), ('ghibli', 'Studio Ghibli'), ('pixel', 'Pixel Art'), ('sketch', 'Sketch')], default='cartoon', max_length=20),
        ),
        migrations.AlterField(
            model_name='ttssettings',
            name='speed',
            field=models.CharField(choices=[('0.5', '0.5× Very Slow'), ('0.75', '0.75× Slow'), ('1.0', '1.0× Normal'), ('1.25', '1.25× Fast'), ('1.5', '1.5× Faster'), ('2.0', '2.0× Very Fast')], default='1.0', max_length=10),
        ),
    ]
