# Generated by Django 6.0.3 on 2026-03-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0007_add_voice_gender_update_speed_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rewriting_story', 'Rewriting Story'), ('story_rewritten', 'Story Rewritten'), ('splitting_story', 'Splitting Story'), ('processing_segments', 'Processing Segments'), ('merging_video', 'Merging Video'), ('done', 'Done'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
