# Generated by Django 6.0.3 on 2026-03-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_pipeline', '0008_add_stopped_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storysegment',
            name='image_path',
        ),
        migrations.AddField(
            model_name='storyjob',
            name='diffusion_model',
            field=models.CharField(choices=[('flux-schnell', 'FLUX.1 Schnell (Fast, great quality)'), ('flux-dev', 'FLUX.1 Dev (Slower, best quality)'), ('sdxl', 'Stable Diffusion XL')], default='flux-schnell', max_length=20),
        ),
        migrations.AddField(
            model_name='storysegment',
            name='image_paths',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='ttssettings',
            name='diffusion_model',
            field=models.CharField(choices=[('flux-schnell', 'FLUX.1 Schnell (Fast, great quality)'), ('flux-dev', 'FLUX.1 Dev (Slower, best quality)'), ('sdxl', 'Stable Diffusion XL')], default='flux-schnell', max_length=20),
        ),
    ]
